Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/warproxxx/Desktop/Projects/algorithms/algos/altcoin/bot.py", line 237, in alt_bot
    daily_tasks()
  File "/home/warproxxx/Desktop/Projects/algorithms/algos/altcoin/bot.py", line 144, in daily_tasks
    lt.fill_order('open', row['backtest_position'].lower())
  File "/home/warproxxx/Desktop/Projects/algorithms/algos/altcoin/live_trader.py", line 315, in fill_order
    if method == "attempt_limit":
  File "/home/warproxxx/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 1326, in __nonzero__
    raise ValueError(
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
